### ISSUE TITLE
Version 1.1.1 gets stuck on Initializing CD

### ISSUE THREAD

**Issue by pcortesduoc** [alex-free/tonyhax#2]
**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta.

-  tonyhax-v1.1.1-international in Slot 2

**Installation method**: How did you get tonyhax on the memory card?

-  Through memory card annihilator 2.0, using the restore image option. I used tonyhax_scph-7000_slot2.mcr

**Entry point game**: Which game are you using to launch tonyhax?

- None
    
**Console model**: Console product code, written on the bottom of the unit, such as "SCPH-7502"

- SCPH-7000

**Integrity check**: If it boots, does the built-in integrity check succeed?

- Yes

**BIOS version**: If you can get to boot, which version of the BIOS does it report?

- Sys BIOS: 4.0 08/18/97 J
- CD BIOS: C2140897

**Target game**: If the bug happens when launching a game, what's its name and game code? Example: "Spyro 3 (SCES-02835)"

- It occurs on any game

**Bug explanation**:
Please write a detailed explanation on which issue are you experiencing.

- When I try to launch any burned game on version 1.1.1, it gets stuck on "Initializing CD" after calibrating the laser.  So, the menu loads up fine, the prompt to close the lid for the region check goes fine, then when the disc stops, I swap it with a CD-R and press X, the new disc spins up, it stops briefly for the laser calibration, then continues to spin as it says "Initializing CD", but the screen doesn't progress any further than that. This happens with any burned CD-R, burned at either 10X or 24X. I've used Maxell (Ritek I believe), Master-G (CMC i believe) and Verbatim DataLifePlus (MCC).
- **This issue doesn't happen in version 1.1.0**. The Verbatim and sometimes the Master-G discs load up fine on that version.
- I tested this on 2 different Sony memory cards.
- Originally, I installed v1.1.0 and it worked fine. Then, when 1.1.1 came out, I managed to get memory card annihilator to install 1.1.1 on it without formatting it first. When I tested it, it loaded fine into the tonyhax menu, but it always got stuck on Initializing CD.
- Today I formatted that card with MCTool. Then, I Installed 1.1.0 on it again, tested it and verified it worked correctly. Then I formatted it, installed 1.1.1 on it and verified that it once again didn't work, getting stuck on Initializing CD just like before. Then I formatted it again and reinstalled 1.1.0 again, and it started working like normal.
- I did something similar with my other memory card, installing both versions and getting the same results.
- **So for now, the workaround is to go back to 1.1.0**

**Comment by alex-free** [comment]
Should be fixed in v1.1.2. Please let me know if it is not.

**Comment by pcortesduoc** [comment]
I've tested v1.1.2 with multiple discs and it seems to be working fine so far. I also burned Dino Crisis USA and the copy protection patch is working fine as well. Thank you very much for your work :)

I just double checked and my Verbatim discs are actually Mitshubishi, thankfully. Though they still have issues with video and audio skipping, but they work fine if I lift my console about 30 degrees on any side lol. I guess I'll have to follow your drive service manual in the future.

**Comment by alex-free** [comment]
> I've tested v1.1.2 with multiple discs and it seems to be working fine so far. I also burned Dino Crisis USA and the copy protection patch is working fine as well. Thank you very much for your work :)
> 
> I just double checked and my Verbatim discs are actually Mitshubishi, thankfully. Though they still have issues with video and audio skipping, but they work fine if I lift my console about 30 degrees on any side lol. I guess I'll have to follow your drive service manual in the future.

The console's orientation affecting it's ability to read discs makes it a good candidate for the guide. I've fixed a bunch that work like that.

I'm currently playing Dino Crisis actually for the first time:)

Really happy you finally got to see everything working.
